

FROM node:20-alpine

WORKDIR /app

# Copia arquivos para instalar dependências
COPY package*.json ./


RUN npm install

# Copia todo o código fonte
COPY src ./src

# Comando para rodar o serviço
CMD ["npm", "run", "start:pag"]
